Script started on Sat 16 May 2015 01:30:42 PM PDT
~
kchan049@hammer $ s[Kcs100
[0;91m
===============================================================================
|                                                                             |
| You have enabled settings specific for cs100.  Everything you do is being   |
| recorded to measure your progress in the class.                             |
|                                                                             |
| Important commands for the class:                                           |
|   * calcgrade.sh          displays a detailed breakdown of your grade       |
|   * checksyscalls.sh      is your cpp file doing proper error checking?     |
|   * typespeed             practice typing unix commands                     |
|                                                                             |
| Important commands for general C++ programming:                             |
|   * make                  don't call g++ manually; let make do the work!    |
|   * gdb                   the GNU debugger                                  |
|   * valgrind              get rid of your memory leaks                      |
|   * cppcheck              static analysis tool                              |
|   * man                   find help about any syscall / terminal command    |
|                                                                             |
===============================================================================
[0m
[s%%%%%%%%%%[u[0;32mkchan049[0;36m@[0;32mcs100[0;36m:[0;32m~[0;95m [0;36m$[0m cd Desktop/cs100/rshell/
[s%%%%%%%%%%[u[0;32mkchan049[0;36m@[0;32mcs100[0;36m:[0;32m~/Desktop/cs100/rshell[0;95m (master) [0;36m$[0m bin/rhsel[K[K[K[Khell[K[K[K[Kshell
bash: bin/rshell: No such file or directory
[s%%%%%%%%%%[u[0;32mkchan049[0;36m@[0;32mcs100[0;36m:[0;32m~/Desktop/cs100/rshell[0;95m (master) [0;36m$[0m make rshell
mkdir -p ./bin
g++ -Wall -Werror -pedantic -ansi  ./src/exec.cpp -o ./bin/rshell
[s%%%%%%%%%%[u[0;32mkchan049[0;36m@[0;32mcs100[0;36m:[0;32m~/Desktop/cs100/rshell[0;95m (master) [0;36m$[0m bin/rshell
kchan049@hammer.cs.ucr.edu$ #input redirection
kchan049@hammer.cs.ucr.edu$ #creating an existing file
kchan049@hammer.cs.ucr.edu$ ls -a > test
kchan049@hammer.cs.ucr.edu$ cat < test
.
..
bin
.git
LICENSE
Makefile
README.md
src
test
tests
kchan049@hammer.cs.ucr.edu$ #nonexisting file
kchan049@hammer.cs.ucr.edu$ cat < test1
open: No such file or directory
in: No such file or directory
^C
[s%%%%%%%%%%[u[0;32mkchan049[0;36m@[0;32mcs100[0;36m:[0;32m~/Desktop/cs100/rshell[0;95m (master) [0;36m$[0m bin/rshell
kchan049@hammer.cs.ucr.edu$ cat      <      test
.
..
bin
.git
LICENSE
Makefile
README.md
src
test
tests
kchan049@hammer.cs.ucr.edu$      cat      <    test
.
..
bin
.git
LICENSE
Makefile
README.md
src
test
tests
kchan049@hammer.cs.ucr.edu$ cat<test
.
..
bin
.git
LICENSE
Makefile
README.md
src
test
tests
kchan049@hammer.cs.ucr.edu$ cat < test | ls -a
.
..
bin
.git
LICENSE
Makefile
README.md
src
test
tests
kchan049@hammer.cs.ucr.edu$ #output redirection
kchan049@hammer.cs.ucr.edu$ ls -a > test1
kchan049@hammer.cs.ucr.edu$ cat < test1
.
..
bin
.git
LICENSE
Makefile
README.md
src
test
test1
tests
kchan049@hammer.cs.ucr.edu$ ls -a > abc
kchan049@hammer.cs.ucr.edu$ cat < abc
.
..
abc
bin
.git
LICENSE
Makefile
README.md
src
test
test1
tests
kchan049@hammer.cs.ucr.edu$ ls -a >>>         
kchan049@hammer.cs.ucr.edu$ 
kchan049@hammer.cs.ucr.edu$ ls -a >> abc
kchan049@hammer.cs.ucr.edu$ cat < abc
.
..
abc
bin
.git
LICENSE
Makefile
README.md
src
test
test1
tests
.
..
abc
bin
.git
LICENSE
Makefile
README.md
src
test
test1
tests
kchan049@hammer.cs.ucr.edu$ ls -a >> abcd
kchan049@hammer.cs.ucr.edu$ cat < abcd
.
..
abc
abcd
bin
.git
LICENSE
Makefile
README.md
src
test
test1
tests
kchan049@hammer.cs.ucr.edu$    ls    -a    >    dad
kchan049@hammer.cs.ucr.edu$ cat < dad
.
..
abc
abcd
bin
dad
.git
LICENSE
Makefile
README.md
src
test
test1
tests
kchan049@hammer.cs.ucr.edu$     ls    -a >>     dad
kchan049@hammer.cs.ucr.edu$ cat < dad
.
..
abc
abcd
bin
dad
.git
LICENSE
Makefile
README.md
src
test
test1
tests
.
..
abc
abcd
bin
dad
.git
LICENSE
Makefile
README.md
src
test
test1
tests
kchan049@hammer.cs.ucr.edu$ ls -a>mom
kchan049@hammer.cs.ucr.edu$ cat < mom
.
..
abc
abcd
bin
dad
.git
LICENSE
Makefile
mom
README.md
src
test
test1
tests
kchan049@hammer.cs.ucr.edu$ ls -a>>moms
kchan049@hammer.cs.ucr.edu$ cat < moms
.
..
abc
abcd
bin
dad
.git
LICENSE
Makefile
mom
moms
README.md
src
test
test1
tests
kchan049@hammer.cs.ucr.edu$ #piping
kchan049@hammer.cs.ucr.edu$ ls | ls
abc   bin  LICENSE   mom   README.md  test   tests
abcd  dad  Makefile  moms  src	      test1
kchan049@hammer.cs.ucr.edu$ ls | grep e
Makefile
test
test1
tests
kchan049@hammer.cs.ucr.edu$ ls | grep e | grep t
test
test1
tests
kchan049@hammer.cs.ucr.edu$ ls      |       grep e     e
Makefile
test
test1
tests
kchan049@hammer.cs.ucr.edu$   ls    |   grep    e
Makefile
test
test1
tests
kchan049@hammer.cs.ucr.edu$ ls|grep e
Makefile
test
test1
tests
kchan049@hammer.cs.ucr.edu$ ls | ls > www
kchan049@hammer.cs.ucr.edu$ cat < www
abc
abcd
bin
dad
LICENSE
Makefile
mom
moms
README.md
src
test
test1
tests
www
kchan049@hammer.cs.ucr.edu$ cat < test1 | ls -a | cat > test2
kchan049@hammer.cs.ucr.edu$ cat < test2
.
..
bin
.git
LICENSE
Makefile
README.md
src
test
test1
tests
kchan049@hammer.cs.ucr.edu$ #extra credit 1
kchan049@hammer.cs.ucr.edu$ cat <<< "extra credit rocks!"
extra credit rocks!
kchan049@hammer.cs.ucr.edu$ cat <<< "extra credit rocks!" > extra

kchan049@hammer.cs.ucr.edu$ cat < extra
extra credit rocks!kchan049@hammer.cs.ucr.edu$ cat <<< "extra"
extra
kchan049@hammer.cs.ucr.edu$ cat<<<"extracredit"
extracredit
kchan049@hammer.cs.ucr.edu$ #newline recorded in my README for extra credit as a bug
kchan049@hammer.cs.ucr.edu$ #extra credit 2
kchan049@hammer.cs.ucr.edu$ ls -a 1> asdf
kchan049@hammer.cs.ucr.edu$ cat < asdf
.
..
abc
abcd
asdf
bin
dad
extra
.git
LICENSE
Makefile
mom
moms
README.md
src
test
test1
test2
tests
www
kchan049@hammer.cs.ucr.edu$ ls -a 1>> asdf
kchan049@hammer.cs.ucr.edu$ cat < asdf
.
..
abc
abcd
asdf
bin
dad
extra
.git
LICENSE
Makefile
mom
moms
README.md
src
test
test1
test2
tests
www
.
..
abc
abcd
asdf
bin
dad
extra
.git
LICENSE
Makefile
mom
moms
README.md
src
test
test1
test2
tests
www
kchan049@hammer.cs.ucr.edu$ tocu    #missedtyped
kchan049@hammer.cs.ucr.edu$ g 
kchan049@hammer.cs.ucr.edu$ 
kchan049@hammer.cs.ucr.edu$ 
kchan049@hammer.cs.ucr.edu$ 
kchan049@hammer.cs.ucr.edu$ 
kchan049@hammer.cs.ucr.edu$ 
kchan049@hammer.cs.ucr.edu$ 
kchan049@hammer.cs.ucr.edu$ 
kchan049@hammer.cs.ucr.edu$ 
kchan049@hammer.cs.ucr.edu$ 
kchan049@hammer.cs.ucr.edu$ touch dad.cpp
kchan049@hammer.cs.ucr.edu$ g++ touch.cpp 2> asdf'                      #miss typed again
kchan049@hammer.cs.ucr.edu$ 
kchan049@hammer.cs.ucr.edu$ 
kchan049@hammer.cs.ucr.edu$ 
kchan049@hammer.cs.ucr.edu$ 
kchan049@hammer.cs.ucr.edu$ g++ touch.cpp 2> asdf
kchan049@hammer.cs.ucr.edu$ cat < asdf
g++: error: touch.cpp: No such file or directory
g++: fatal error: no input files
compilation terminated.
kchan049@hammer.cs.ucr.edu$ gi  
kchan049@hammer.cs.ucr.edu$ 
kchan049@hammer.cs.ucr.edu$ g++ touh        
kchan049@hammer.cs.ucr.edu$ 

kchan049@hammer.cs.ucr.edu$ kchan049@hammer.cs.ucr.edu$ g 
kchan049@hammer.cs.ucr.edu$ 
kchan049@hammer.cs.ucr.edu$ g++ touch.cpp 2>> asdf
kchan049@hammer.cs.ucr.edu$ cat < asdf
g++: error: touch.cpp: No such file or directory
g++: fatal error: no input files
compilation terminated.
g++: error: touch.cpp: No such file or directory
g++: fatal error: no input files
compilation terminated.
kchan049@hammer.cs.ucr.edu$ #extra credit 1 and 2 work
kchan049@hammer.cs.ucr.edu$ #done with script
kchan049@hammer.cs.ucr.edu$ exit
[s%%%%%%%%%%[u[0;32mkchan049[0;36m@[0;32mcs100[0;36m:[0;32m~/Desktop/cs100/rshell[0;95m (master) [0;36m$[0m exit
exit
do_ypcall: clnt_call: RPC: Unable to send; errno = Operation not permitted
~
kchan049@hammer $ exit
exit

Script done on Sat 16 May 2015 01:44:49 PM PDT
