Script started on Sat 16 May 2015 01:03:36 PM PDT
~
kchan049@hammer $ cs100
[0;91m
===============================================================================
|                                                                             |
| You have enabled settings specific for cs100.  Everything you do is being   |
| recorded to measure your progress in the class.                             |
|                                                                             |
| Important commands for the class:                                           |
|   * calcgrade.sh          displays a detailed breakdown of your grade       |
|   * checksyscalls.sh      is your cpp file doing proper error checking?     |
|   * typespeed             practice typing unix commands                     |
|                                                                             |
| Important commands for general C++ programming:                             |
|   * make                  don't call g++ manually; let make do the work!    |
|   * gdb                   the GNU debugger                                  |
|   * valgrind              get rid of your memory leaks                      |
|   * cppcheck              static analysis tool                              |
|   * man                   find help about any syscall / terminal command    |
|                                                                             |
===============================================================================
[0m
[s%%%%%%%%%%[u[0;32mkchan049[0;36m@[0;32mcs100[0;36m:[0;32m~[0;95m [0;36m$[0m ls
assn3.asm  assn4.asm  assn5.asm  assn6.asm  Desktop  Downloads	lab5
[s%%%%%%%%%%[u[0;32mkchan049[0;36m@[0;32mcs100[0;36m:[0;32m~[0;95m [0;36m$[0m cd Dektop[K[K[K[Ksktop/cs100/rshell/
[s%%%%%%%%%%[u[0;32mkchan049[0;36m@[0;32mcs100[0;36m:[0;32m~/Desktop/cs100/rshell[0;95m (master) [0;36m$[0m ls
bin  dad  LICENSE  Makefile  README.md	src  tests
[s%%%%%%%%%%[u[0;32mkchan049[0;36m@[0;32mcs100[0;36m:[0;32m~/Desktop/cs100/rshell[0;95m (master) [0;36m$[0m bin/rshell
kchan049@hammer.cs.ucr.edu$ #input drei    redirection
kchan049@hammer.cs.ucr.edu$ ls -a > test
kchan049@hammer.cs.ucr.edu$ cat     #  existing file              cat < test
.
..
bin
dad
.git
LICENSE
Makefile
README.md
src
test
tests

kchan049@hammer.cs.ucr.edu$ cat < test1 t100    100
open: No such file or directory
in: No such file or directory
^C
[s%%%%%%%%%%[u[0;32mkchan049[0;36m@[0;32mcs100[0;36m:[0;32m~/Desktop/cs100/rshell[0;95m (master) [0;36m$[0m bin/rshell 
kchan049@hammer.cs.ucr.edu$ cat      <     test
.
..
bin
dad
.git
LICENSE
Makefile
README.md
src
test
tests

kchan049@hammer.cs.ucr.edu$ cat      cat    <    test
.
..
bin
dad
.git
LICENSE
Makefile
README.md
src
test
tests

kchan049@hammer.cs.ucr.edu$ cat<test
.
..
bin
dad
.git
LICENSE
Makefile
README.md
src
test
tests

kchan049@hammer.cs.ucr.edu$ cat < test | ls -a
.
..
bin
dad
.git
LICENSE
Makefile
README.md
src
test
tests

kchan049@hammer.cs.ucr.edu$ #output redirc ection
kchan049@hammer.cs.ucr.edu$ ls -a > test1
kchan049@hammer.cs.ucr.edu$ cat < test1
.
..
bin
dad
.git
LICENSE
Makefile
README.md
src
test
test1
tests

kchan049@hammer.cs.ucr.edu$ ls -a > abc
kchan049@hammer.cs.ucr.edu$ cat < abc
.
..
abc
bin
dad
.git
LICENSE
Makefile
README.md
src
test
test1
tests

kchan049@hammer.cs.ucr.edu$ ls -a >> abcd
kchan049@hammer.cs.ucr.edu$ cat < abcd
.
..
abc
abcd
bin
dad
.git
LICENSE
Makefile
README.md
src
test
test1
tests

kchan049@hammer.cs.ucr.edu$ ls -a >> abc
kchan049@hammer.cs.ucr.edu$ cat < abc
.
..
abc
bin
dad
.git
LICENSE
Makefile
README.md
src
test
test1
tests
.
..
abc
abcd
bin
dad
.git
LICENSE
Makefile
README.md
src
test
test1
tests

kchan049@hammer.cs.ucr.edu$ ls -a >> 111
kchan049@hammer.cs.ucr.edu$ cat < 111
.
..
111
abc
abcd
bin
dad
.git
LICENSE
Makefile
README.md
src
test
test1
tests

kchan049@hammer.cs.ucr.edu$ ls -a>          ls   -a    >     dad
kchan049@hammer.cs.ucr.edu$ cat < dad
.
..
111
abc
abcd
bin
dad
.git
LICENSE
Makefile
README.md
src
test
test1
tests

kchan049@hammer.cs.ucr.edu$ ls        ls -a          >dad   mom
kchan049@hammer.cs.ucr.edu$ cat < mom
.
..
111
abc
abcd
bin
dad
.git
LICENSE
Makefile
mom
README.md
src
test
test1
tests

kchan049@hammer.cs.ucr.edu$ ls                 ls     -a    >>     wat
kchan049@hammer.cs.ucr.edu$ cat < wat
.
..
111
abc
abcd
bin
dad
.git
LICENSE
Makefile
mom
README.md
src
test
test1
tests
wat

kchan049@hammer.cs.ucr.edu$ ls -a>wat   watthe
kchan049@hammer.cs.ucr.edu$ cat < watthe
.
..
111
abc
abcd
bin
dad
.git
LICENSE
Makefile
mom
README.md
src
test
test1
tests
wat
watthe

kchan049@hammer.cs.ucr.edu$ #piping
kchan049@hammer.cs.ucr.edu$ ls | ls
111  abcd  dad	    Makefile  README.md  test	tests  watthe
abc  bin   LICENSE  mom       src	 test1	wat
kchan049@hammer.cs.ucr.edu$ ls ||  grep e
Makefile
test
test1
tests
watthe
kchan049@hammer.cs.ucr.edu$ ls | grep e | grep t
test
test1
tests
watthe
kchan049@hammer.cs.ucr.edu$ ls     |     grep   e
Makefile
test
test1
tests
watthe
kchan049@hammer.cs.ucr.edu$ ls|grep e
Makefile
test
test1
tests
watthe
kchan049@hammer.cs.ucr.edu$ ls | ls > www
kchan049@hammer.cs.ucr.edu$ cat < www
111
abc
abcd
bin
dad
LICENSE
Makefile
mom
README.md
src
test
test1
tests
wat
watthe
www

kchan049@hammer.cs.ucr.edu$ 
kchan049@hammer.cs.ucr.edu$ cat < test1 | ls -a | cat > test2

kchan049@hammer.cs.ucr.edu$ cat < test2
.
..
bin
dad
.git
LICENSE
Makefile
README.md
src
test
test1
tests

kchan049@hammer.cs.ucr.edu$ #extra credit 1
kchan049@hammer.cs.ucr.edu$ cat <<< "extra crei dit rocks"
extra credit rocks
kchan049@hammer.cs.ucr.edu$ cat <<< "extra credit rocks  " > extra

kchan049@hammer.cs.ucr.edu$ cat < extra
extra credit rocks
kchan049@hammer.cs.ucr.edu$ cat      <<<      "extra credit rocks"
extra credit rocks
kchan049@hammer.cs.ucr.edu$ cat<<<"extracreditrocks"
extracreditrocks
kchan049@hammer.cs.ucr.edu$ #extra credit 2
kchan049@hammer.cs.ucr.edu$ ls -a 1> asdf
kchan049@hammer.cs.ucr.edu$ cat < asdf
.
..
111
abc
abcd
asdf
bin
dad
extra
.git
LICENSE
Makefile
mom
README.md
src
test
test1
test2
tests
wat
watthe
www

kchan049@hammer.cs.ucr.edu$ ls -a 1>> asdf
kchan049@hammer.cs.ucr.edu$ cat < asdf
.
..
111
abc
abcd
asdf
bin
dad
extra
.git
LICENSE
Makefile
mom
README.md
src
test
test1
test2
tests
wat
watthe
www
.
..
111
abc
abcd
asdf
bin
dad
extra
.git
LICENSE
Makefile
mom
README.md
src
test
test1
test2
tests
wat
watthe
www

kchan049@hammer.cs.ucr.edu$ g++   touch dad.cpp
kchan049@hammer.cs.ucr.edu$ g++ touch.cpp 2> asdf
kchan049@hammer.cs.ucr.edu$ cat < asdf
g++: error: touch.cpp: No such file or directory
g++: fatal error: no input files
compilation terminated.

kchan049@hammer.cs.ucr.edu$ g++ touch.cpp 2>> asdf
kchan049@hammer.cs.ucr.edu$ cat < asdf
g++: error: touch.cpp: No such file or directory
g++: fatal error: no input files
compilation terminated.
g++: error: touch.cpp: No such file or directory
g++: fatal error: no input files
compilation terminated.

kchan049@hammer.cs.ucr.edu$ #done with scripting
kchan049@hammer.cs.ucr.edu$ exit
[s%%%%%%%%%%[u[0;32mkchan049[0;36m@[0;32mcs100[0;36m:[0;32m~/Desktop/cs100/rshell[0;95m (master) [0;36m$[0m exit
exit
~
kchan049@hammer $ exit
exit

Script done on Sat 16 May 2015 01:20:27 PM PDT
