Script started on Fri 29 May 2015 03:03:23 PM PDT
~
kchan049@hammer $ cd Desktop/cs100/rshell/
~/Desktop/cs100/rshell
kchan049@hammer $ bin/rshell 
kchan049@hammer.cs.ucr.edu:~/Desktop/cs100/rshell$ #testing absolute path
kchan049@hammer.cs.ucr.edu:~/Desktop/cs100/rshell$ cd /home
kchan049@hammer.cs.ucr.edu:/home$ cd -
kchan049@hammer.cs.ucr.edu:~/Desktop/cs100/rshell$ #testing cd -
kchan049@hammer.cs.ucr.edu:~/Desktop/cs100/rshell$ cd -
kchan049@hammer.cs.ucr.edu:/home$ cd -
kchan049@hammer.cs.ucr.edu:~/Desktop/cs100/rshell$ #testing cd alone
kchan049@hammer.cs.ucr.edu:~/Desktop/cs100/rshell$ cd
kchan049@hammer.cs.ucr.edu:~$ #testing cd path up directories
kchan049@hammer.cs.ucr.edu:~$ cd Desktop
kchan049@hammer.cs.ucr.edu:~/Desktop$ cd cs100/rshell
kchan049@hammer.cs.ucr.edu:~/Desktop/cs100/rshell$ #testing cd .
kchan049@hammer.cs.ucr.edu:~/Desktop/cs100/rshell$ cd .
kchan049@hammer.cs.ucr.edu:~/Desktop/cs100/rshell$ #supposed to stay in directory and it did that in fact
kchan049@hammer.cs.ucr.edu:~/Desktop/cs100/rshell$ #testing cd .. to go back a directory
kchan049@hammer.cs.ucr.edu:~/Desktop/cs100/rshell$ cd ..
kchan049@hammer.cs.ucr.edu:~/Desktop/cs100$ #testing cd nonexistent directory
kchan049@hammer.cs.ucr.edu:~/Desktop/cs100$ cd 123
chdir: No such file or directory
kchan049@hammer.cs.ucr.edu:~/Desktop/cs100$ #testing control c
kchan049@hammer.cs.ucr.edu:~/Desktop/cs100$ #control c doesnt completely stop the rshell
kchan049@hammer.cs.ucr.edu:~/Desktop/cs100$ ^C
kchan049@hammer.cs.ucr.edu:~/Desktop/cs100$ ^C
kchan049@hammer.cs.ucr.edu:~/Desktop/cs100$ ^C
kchan049@hammer.cs.ucr.edu:~/Desktop/cs100$ #control c will end process with siginit sigint
kchan049@hammer.cs.ucr.edu:~/Desktop/cs100$ cat
hi
hi
hi
hi
^Ckchan049@hammer.cs.ucr.edu:~/Desktop/cs100$ #extra credit
kchan049@hammer.cs.ucr.edu:~/Desktop/cs100$ #control z will pause program with sigstop
kchan049@hammer.cs.ucr.edu:~/Desktop/cs100$ #we will demonstrate with the program similar in lab with the inifitely loop printing hi with sleep(1)
kchan049@hammer.cs.ucr.edu:~/Desktop/cs100$ ls
kchan049@hammer.cs.ucr.edu:~/Desktop/cs100$ clone  hw1  kenta.cpp  lab1  lab2  lab3  lab4  lab6  ls  rshell  ucr-cs100

kchan049@hammer.cs.ucr.edu:~/Desktop/cs100$ cd rs	     
kchan049@hammer.cs.ucr.edu:~/Desktop/cs100$ cd rshell
kchan049@hammer.cs.ucr.edu:~/Desktop/cs100/rshell$ ls
kchan049@hammer.cs.ucr.edu:~/Desktop/cs100/rshell$ bin  LICENSE  Makefile	README.md  src	tests

kchan049@hammer.cs.ucr.edu:~/Desktop/cs100/rshell$ cd src
kchan049@hammer.cs.ucr.edu:~/Desktop/cs100/rshell/src$ ./tests 
kchan049@hammer.cs.ucr.edu:~/Desktop/cs100/rshell/src$ hi
hi
hi
hi
hi
hi
^ZStopped!

kchan049@hammer.cs.ucr.edu:~/Desktop/cs100/rshell/src$ #control z worked
kchan049@hammer.cs.ucr.edu:~/Desktop/cs100/rshell/src$ #now lets try using fg
kchan049@hammer.cs.ucr.edu:~/Desktop/cs100/rshell/src$ fg
kchan049@hammer.cs.ucr.edu:~/Desktop/cs100/rshell/src$ hi
hi
hi
hi
hi
hi
^ZStopped!

kchan049@hammer.cs.ucr.edu:~/Desktop/cs100/rshell/src$ #fg worked too so lets now try bg
kchan049@hammer.cs.ucr.edu:~/Desktop/cs100/rshell/src$ #since ctrl z wont work on bg since process is in background we need to tuype kill -9 pid
kchan049@hammer.cs.ucr.edu:~/Desktop/cs100/rshell/src$ bg
kchan049@hammer.cs.ucr.edu:~/Desktop/cs100/rshell/src$ hi
hi
hi
pshi

  PID TTY          TIME CMD
 9366 pts/16   00:00:00 bash
 9369 pts/16   00:00:00 rshell
11057 pts/16   00:00:00 test
11299 pts/16   00:00:00 ps
kchan049@hammer.cs.ucr.edu:~/Desktop/cs100/rshell/src$ kihi
ll hi
-9hi
 hi
hi
110hi
57hi

kchan049@hammer.cs.ucr.edu:~/Desktop/cs100/rshell/src$ #bg worked!
kchan049@hammer.cs.ucr.edu:~/Desktop/cs100/rshell/src$ #we now will test extra credit for the ~ sign
kchan049@hammer.cs.ucr.edu:~/Desktop/cs100/rshell/src$ # i will go back directories until ~ sign disappears
kchan049@hammer.cs.ucr.edu:~/Desktop/cs100/rshell/src$ cd ..
kchan049@hammer.cs.ucr.edu:~/Desktop/cs100/rshell$ cd ..
kchan049@hammer.cs.ucr.edu:~/Desktop/cs100$ cd ../..
kchan049@hammer.cs.ucr.edu:~$ cd ..
kchan049@hammer.cs.ucr.edu:/home/csmajs$ #extra credit rocks!
kchan049@hammer.cs.ucr.edu:/home/csmajs$ exit
~/Desktop/cs100/rshell
kchan049@hammer $ exit
exit

Script done on Fri 29 May 2015 03:09:15 PM PDT
